SELECT 
 DOC.ID AS "组号", 
 DETAIL.ID AS "移位单明细.序号", 
 (DETAIL.PLAN_QUANTITY_BU-DETAIL.ALLOCATED_QUANTITY_BU) AS "移位单明细.未分配数量",
 DETAIL.SOI AS "移位单明细.SOI",
 DETAIL.SUPPLIER AS "移位单明细.供应商",
 DETAIL.EXTEND_PROPC1 AS "移位单明细.扩展属性1",
 DETAIL.EXTEND_PROPC2 AS "移位单明细.扩展属性2",
 DETAIL.EXTEND_PROPC3 AS "移位单明细.扩展属性3",
 DETAIL.EXTEND_PROPC4 AS "移位单明细.扩展属性4",
 DETAIL.EXTEND_PROPC5 AS "移位单明细.扩展属性5",
 DETAIL.EXTEND_PROPC6 AS "移位单明细.扩展属性6",
 DETAIL.EXTEND_PROPC7 AS "移位单明细.扩展属性7",
 DETAIL.EXTEND_PROPC8 AS "移位单明细.扩展属性8",
 DETAIL.EXTEND_PROPC9 AS "移位单明细.扩展属性9",
 DETAIL.EXTEND_PROPC10 AS "移位单明细.扩展属性10",
 DETAIL.EXTEND_PROPC11 AS "移位单明细.扩展属性11",
 DETAIL.EXTEND_PROPC12 AS "移位单明细.扩展属性12",
 DETAIL.EXTEND_PROPC13 AS "移位单明细.扩展属性13",
 DETAIL.EXTEND_PROPC14 AS "移位单明细.扩展属性14",
 DETAIL.EXTEND_PROPC15 AS "移位单明细.扩展属性15",
 DETAIL.EXTEND_PROPC16 AS "移位单明细.扩展属性16",
 DETAIL.EXTEND_PROPC17 AS "移位单明细.扩展属性17",
 DETAIL.EXTEND_PROPC18 AS "移位单明细.扩展属性18",
 DETAIL.EXTEND_PROPC19 AS "移位单明细.扩展属性19",
 DETAIL.EXTEND_PROPC20 AS "移位单明细.扩展属性20",
 LOC.ID AS "移位单明细.备货库位序号"
 FROM WMS_MOVE_DOC_DETAIL DETAIL
 LEFT JOIN WMS_MOVE_DOC DOC ON DETAIL.MOVE_DOC_ID=DOC.ID 
 LEFT JOIN WMS_LOCATION LOC ON DOC.SHIP_LOCATION_ID=LOC.ID
 WHERE 1=1 AND DOC.BE_CROSS_DOCK='Y' AND DOC.STATUS IN ('OPEN', 'WORKING')
 /~仓库ID: AND DOC.WAREHOUSE_ID = {仓库ID}~/
 /~货品ID: AND DETAIL.ITEM_ID = {货品ID}~/
 /~相关单号: AND DOC.RELATED_BILL1 = {相关单号}~/