SELECT 
 LOC.WAREHOUSE_ID AS "组号",
 ITEM.ID AS "货品序号",
 ITEM.CODE AS "货品代码",
 SUM(INV.QUANTITY_BU + INV.PUTAWAY_QUANTITY_BU - INV.ALLOCATED_QUANTITY_BU) AS "库存可用数量"
 FROM WMS_INVENTORY INV
 LEFT JOIN WMS_ITEM_KEY IK ON IK.ID = INV.ITEM_KEY_ID
 LEFT JOIN WMS_ITEM ITEM ON ITEM.ID = IK.ITEM_ID
 LEFT JOIN WMS_LOCATION LOC ON LOC.ID = INV.LOCATION_ID
 WHERE 1=1
 AND LOC.STATUS = 'ENABLED'
 AND LOC.COUNT_LOCK = 'N'
 AND LOC.TYPE = 'STORAGE'
 AND LOC.ZONE_NO > 0
 /~仓库序号: AND LOC.WAREHOUSE_ID = {仓库序号}~/
 /~货品序号: AND ITEM.ID = {货品序号}~/
 AND (LOC.ID IN (SELECT LOCATION.ID
       FROM WMS_LOCATION LOCATION
 		LEFT JOIN WMS_ZONE AREA ON AREA.ID = LOCATION.ZONE_ID
       WHERE 1 <> 1
       /~补货区拼接条件: OR #{补货区拼接条件}~/
	)
 )
 GROUP BY LOC.WAREHOUSE_ID, ITEM.ID, ITEM.CODE
 