SELECT
 TASK.STATUS AS "组号",
 TASK.RELATED_BILL AS "订单.单号",
 TASK.ID AS "订单.任务.任务ID",
 TASK.FROM_LOC_ID AS "订单.任务.移出库位ID",
 TASK.FROM_LOC_CODE AS "订单.任务.移出库位编码",
 FROM_LOC.ZONE_NO AS "订单.任务.移出区",
 FROM_LOC.LINE_NO AS "订单.任务.移出排",
 FROM_AREA.ID AS "订单.任务.移出库区ID",
 FROM_AREA.CODE AS "订单.任务.移出库区编码",
 FROM_AREA.NAME AS "订单.任务.移出库区名称",
 TASK.TO_LOC_ID AS "订单.任务.移入库位ID",
 TASK.TO_LOC_CODE AS "订单.任务.移入库位编码",
 TO_LOC.ZONE_NO AS "订单.任务.移入区",
 TO_LOC.LINE_NO AS "订单.任务.移入排",
 TO_AREA.ID AS "订单.任务.移入库区ID",
 TO_AREA.CODE AS "订单.任务.移入库区编码",
 TO_AREA.NAME AS "订单.任务.移入库区名称",
 TASK.PLAN_QUANTITY_BU AS "订单.任务.件数",
 TASK.PLAN_WEIGHT AS "订单.任务.重量",
 TASK.PLAN_VOLUME AS "订单.任务.体积"
 FROM WMS_TASK TASK 
 LEFT JOIN WMS_MOVE_DOC_DETAIL WMDD ON WMDD.ID = TASK.MOVE_DOC_DETAIL_ID
 LEFT JOIN WMS_MOVE_DOC WMD ON WMD.ID = WMDD.MOVE_DOC_ID
 LEFT JOIN WMS_LOCATION FROM_LOC ON FROM_LOC.ID = TASK.FROM_LOC_ID
 LEFT JOIN WMS_ZONE FROM_AREA ON FROM_AREA.ID = FROM_LOC.ZONE_ID
  LEFT JOIN WMS_LOCATION TO_LOC ON TO_LOC.ID = TASK.TO_LOC_ID
 LEFT JOIN WMS_ZONE TO_AREA ON TO_AREA.ID = TO_LOC.ZONE_ID
 WHERE 1=1 
 AND TASK.STATUS = "OPEN"
 /~移位单序号: AND WMD.ID = {移位单序号}~/
 ORDER BY FROM_LOC.ROUTE_NO ASC
