SELECT 
 INV.STATUS AS "组号",
 INV.ID AS "库存.库存ID", 
 ITEM.CODE AS "库存.货品ID", 
 UNIT.UNIT AS "库存.货品包装",
 INV.STATUS AS "库存.库存状态",
 (INV.QUANTITY_BU - INV.ALLOCATED_QUANTITY_BU) AS "库存.库存数量",
 LOC.ID AS "库存.库位ID",
 ITEM_KEY.STORAGE_DATE AS "库存.存货日期"
 FROM WMS_INVENTORY INV
 LEFT JOIN WMS_ITEM_KEY ITEM_KEY ON ITEM_KEY.ID = INV.ITEM_KEY_ID
 LEFT JOIN WMS_ITEM ITEM ON ITEM.ID = ITEM_KEY.ITEM_ID
 LEFT JOIN WMS_LOCATION LOC ON LOC.ID = INV.LOCATION_ID
 LEFT JOIN WMS_ZONE AREA ON AREA.ID = LOC.ZONE_ID
 LEFT JOIN WMS_PACKAGE_UNIT UNIT ON UNIT.ID = INV.PACKAGE_UNIT_ID
 LEFT JOIN WMS_ORGANIZATION SUP ON SUP.ID = ITEM_KEY.SUPPLIER_ID
WHERE 1=1
 AND LOC.STATUS = 'ENABLED'
 AND LOC.COUNT_LOCK = 'N'
 AND LOC.TYPE = 'STORAGE'
 AND LOC.ZONE_NO > 0 
 AND LOC.EXCEPTION_FLAG = 'N'
 AND INV.QUANTITY_BU - INV.ALLOCATED_QUANTITY_BU > 0
 /~仓库ID: AND LOC.WAREHOUSE_ID = {仓库ID}~/
 /~库区: AND AREA.CODE = {库区}~/
 /~源拣货库位序号: AND LOC.ID <> {源拣货库位序号}~/
 /~区区间开始值: AND LOC.ZONE_NO >= {区区间开始值}~/
 /~区区间结束值: AND LOC.ZONE_NO <= {区区间结束值}~/
 /~排区间开始值: AND LOC.LINE_NO >= {排区间开始值}~/
 /~排区间结束值: AND LOC.LINE_NO <= {排区间结束值}~/
 /~列区间开始值: AND LOC.COL_NO >= {列区间开始值}~/
 /~列区间结束值: AND LOC.COL_NO <= {列区间结束值}~/
 /~层区间开始值: AND LOC.LAYER_NO >= {层区间开始值}~/
 /~层区间结束值: AND LOC.LAYER_NO <= {层区间结束值}~/
 /~货品ID: AND ITEM.ID = {货品ID}~/
 AND (LOC.ID NOT IN (SELECT LOCATION.ID 
       FROM WMS_LOCATION LOCATION
 		LEFT JOIN WMS_ZONE AREA ON AREA.ID = LOCATION.ZONE_ID
       WHERE 1 <> 1
       /~出入锁拼接条件: OR #{出入锁拼接条件}~/
	)
 )
 /~库存状态: AND INV.STATUS = {库存状态}~/
 /~收货单号: AND ITEM_KEY.SOI = {收货单号}~/
 /~供应商: AND SUP.NAME = {供应商}~/
 /~扩展属性1: AND ITEM_KEY.EXTEND_PROPC1 = {扩展属性1}~/
 /~扩展属性2: AND ITEM_KEY.EXTEND_PROPC2 = {扩展属性2}~/
 /~扩展属性3: AND ITEM_KEY.EXTEND_PROPC3 = {扩展属性3}~/
 /~扩展属性4: AND ITEM_KEY.EXTEND_PROPC4 = {扩展属性4}~/
 /~扩展属性5: AND ITEM_KEY.EXTEND_PROPC5 = {扩展属性5}~/
 /~扩展属性6: AND ITEM_KEY.EXTEND_PROPC6 = {扩展属性6}~/
 /~扩展属性7: AND ITEM_KEY.EXTEND_PROPC7 = {扩展属性7}~/
 /~扩展属性8: AND ITEM_KEY.EXTEND_PROPC8 = {扩展属性8}~/
 /~扩展属性9: AND ITEM_KEY.EXTEND_PROPC9 = {扩展属性9}~/
 /~扩展属性10: AND ITEM_KEY.EXTEND_PROPC10 = {扩展属性10}~/
 /~扩展属性11: AND ITEM_KEY.EXTEND_PROPC11 = {扩展属性11}~/
 /~扩展属性12: AND ITEM_KEY.EXTEND_PROPC12 = {扩展属性12}~/
 /~扩展属性13: AND ITEM_KEY.EXTEND_PROPC13 = {扩展属性13}~/
 /~扩展属性14: AND ITEM_KEY.EXTEND_PROPC14 = {扩展属性14}~/
 /~扩展属性15: AND ITEM_KEY.EXTEND_PROPC15 = {扩展属性15}~/
 /~扩展属性16: AND ITEM_KEY.EXTEND_PROPC16 = {扩展属性16}~/
 /~扩展属性17: AND ITEM_KEY.EXTEND_PROPC17 = {扩展属性17}~/
 /~扩展属性18: AND ITEM_KEY.EXTEND_PROPC18 = {扩展属性18}~/
 /~扩展属性19: AND ITEM_KEY.EXTEND_PROPC19 = {扩展属性19}~/
 /~扩展属性20: AND ITEM_KEY.EXTEND_PROPC20 = {扩展属性20}~/
