SELECT 
 LOC.ID AS "序号",
 LOC.CODE AS "代码",
 SUM((INV.QUANTITY_BU + INV.PUTAWAY_QUANTITY_BU)) AS "数量"
 FROM WMS_LOCATION LOC
 LEFT JOIN WMS_ZONE ZONE ON ZONE.ID = LOC.ZONE_ID 
 LEFT JOIN WMS_INVENTORY INV ON INV.LOCATION_ID = LOC.ID 
WHERE 1=1
 AND LOC.STATUS = 'ENABLED'
 AND LOC.TYPE = 'SHIP'
 /~库区序号: AND ZONE.ID = {库区序号}~/
GROUP BY LOC.ID  ORDER BY SUM((INV.QUANTITY_BU + INV.PUTAWAY_QUANTITY_BU))  ASC limit  0,1

