SELECT
 ZONE.ID AS "库区",
 ZONE.CODE AS "工作区.库区编码",
 WORK.ID AS "工作区.工作区序号",
 WORK.CODE AS "工作区.工作区编码"
 FROM WMS_WORK_AREA WORK
 LEFT JOIN WMS_ZONE ZONE ON ZONE.ID = WORK.WAREHOUSE_AREA_ID
 WHERE 1=1 
 AND ZONE.STATUS = "ENABLED"
 /~库区编码: AND ZONE.CODE = {库区编码}~/
