SELECT ITEMKEY.ID AS "组号",
ITEMKEY.STORAGE_DATE AS "存货日期",
ITEMKEY.SOI AS "收货单号",
SUPPLIER.NAME AS "供应商",
ITEMKEY.EXTEND_PROPC1 AS "扩展属性1",
ITEMKEY.EXTEND_PROPC2 AS "扩展属性2",
ITEMKEY.EXTEND_PROPC3 AS "扩展属性3",
ITEMKEY.EXTEND_PROPC4 AS "扩展属性4",
ITEMKEY.EXTEND_PROPC5 AS "扩展属性5",
ITEMKEY.EXTEND_PROPC6 AS "扩展属性6",
ITEMKEY.EXTEND_PROPC7 AS "扩展属性7",
ITEMKEY.EXTEND_PROPC8 AS "扩展属性8",
ITEMKEY.EXTEND_PROPC9 AS "扩展属性9",
ITEMKEY.EXTEND_PROPC10 AS "扩展属性10",
ITEMKEY.EXTEND_PROPC11 AS "扩展属性11",
ITEMKEY.EXTEND_PROPC12 AS "扩展属性12",
ITEMKEY.EXTEND_PROPC13 AS "扩展属性13",
ITEMKEY.EXTEND_PROPC14 AS "扩展属性14",
ITEMKEY.EXTEND_PROPC15 AS "扩展属性15",
ITEMKEY.EXTEND_PROPC16 AS "扩展属性16",
ITEMKEY.EXTEND_PROPC17 AS "扩展属性17",
ITEMKEY.EXTEND_PROPC18 AS "扩展属性18",
ITEMKEY.EXTEND_PROPC19 AS "扩展属性19",
ITEMKEY.EXTEND_PROPC20 AS "扩展属性20"
FROM WMS_ITEM_KEY ITEMKEY 
LEFT JOIN WMS_ORGANIZATION SUPPLIER ON SUPPLIER.ID = ITEMKEY.SUPPLIER_ID
WHERE 1=1
/~批次序号: AND ITEMKEY.ID = {批次序号}~/