SELECT 
 LOC.STATUS AS "组号",
 SUP.CODE AS "库存.供应商",
 ITEM.CODE AS "库存.货品CODE", 
 ITEM_KEY.EXTEND_PROPC1 AS "库存.工艺状态",
 SUM((INV.QUANTITY_BU - INV.ALLOCATED_QUANTITY_BU)) AS "库存.库存数量"
 FROM WMS_INVENTORY INV
 LEFT JOIN WMS_ITEM_KEY ITEM_KEY ON ITEM_KEY.ID = INV.ITEM_KEY_ID
 LEFT JOIN WMS_ITEM ITEM ON ITEM.ID = ITEM_KEY.ITEM_ID
 LEFT JOIN WMS_LOCATION LOC ON LOC.ID = INV.LOCATION_ID
 LEFT JOIN WMS_ZONE AREA ON AREA.ID = LOC.ZONE_ID
 LEFT JOIN WMS_ORGANIZATION SUP ON SUP.ID = ITEM_KEY.SUPPLIER_ID
WHERE 1=1
 AND LOC.STATUS = 'ENABLED'
 AND LOC.TYPE = {库位类型} 
 AND INV.QUANTITY_BU - INV.ALLOCATED_QUANTITY_BU > 0
 AND SUP.CODE IS NOT NULL
 /~仓库ID: AND LOC.WAREHOUSE_ID = {仓库ID}~/
 /~库区: AND AREA.CODE = {库区}~/
 /~区区间开始值: AND LOC.ZONE_NO >= {区区间开始值}~/
 /~区区间结束值: AND LOC.ZONE_NO <= {区区间结束值}~/
 /~排区间开始值: AND LOC.LINE_NO >= {排区间开始值}~/
 /~排区间结束值: AND LOC.LINE_NO <= {排区间结束值}~/
 /~列区间开始值: AND LOC.COL_NO >= {列区间开始值}~/
 /~列区间结束值: AND LOC.COL_NO <= {列区间结束值}~/
 /~层区间开始值: AND LOC.LAYER_NO >= {层区间开始值}~/
 /~层区间结束值: AND LOC.LAYER_NO <= {层区间结束值}~/
 /~供应商: AND SUP.CODE = {供应商}~/
 GROUP BY LOC.STATUS,SUP.CODE,INV.STATUS,ITEM.CODE,ITEM_KEY.EXTEND_PROPC1