SELECT
 MD.WAREHOUSE_ID AS "组号",
 ITEM.CODE AS "货品代码",
 MDD.REPLENISHMENT_AREA AS "补货区",
 SUM(MDD.PLAN_QUANTITY_BU - MDD.ALLOCATED_QUANTITY_BU) AS "待补货数量BU"
 FROM WMS_MOVE_DOC_DETAIL MDD
 LEFT JOIN WMS_MOVE_DOC MD ON MD.ID = MDD.MOVE_DOC_ID
 LEFT JOIN WMS_ITEM ITEM ON ITEM.ID = MDD.ITEM_ID
 WHERE 1=1
 AND MD.TYPE = 'MV_REPLENISHMENT_MOVE'
 AND MD.STATUS IN ('OPEN', 'PARTALLOCATED')
 /~仓库序号: AND MD.WAREHOUSE_ID = {仓库序号}~/
 /~补货区: AND MDD.REPLENISHMENT_AREA = {补货区}~/
 /~货品代码: AND ITEM.CODE = {货品代码}~/
 GROUP BY MD.WAREHOUSE_ID, ITEM.CODE, MDD.REPLENISHMENT_AREA