SELECT
PICK_TICKET.ID AS "序号",
PICK_TICKET.CODE AS "代码",
WMS_BILL_TYPE.NAME AS "单据类型",
COMPANY.NAME AS "货主",
CARRIER.NAME AS "承运商",
DOCK.CODE AS "月台",
PICK_TICKET_DETAIL.ID AS "明细.序号",
PICK_TICKET_DETAIL.LINE_NO AS "明细.行号",
ITEM.ID AS "明细.货品序号",
ITEM.CODE AS "明细.货品代码",
ITEM.NAME AS "明细.货品名称",
ITEM.CLASS1 AS "明细.货品分类",
ITEM.CLASS2 AS "明细.拣货分类",
ITEM.CLASS3 AS "明细.码托分类",
ITEM.CLASS4 AS "明细.ABC分类",
PACKAGE_UNIT.PU_LEVEL AS "明细.包装级别",
PACKAGE_UNIT.CONVERT_FIGURE AS "明细.折算系数",
PACKAGE_UNIT.LINE_NO AS "明细.包装行号",
PACKAGE_UNIT.UNIT AS "明细.包装单位",
PICK_TICKET_DETAIL.EXPECTED_QUANTITY AS "明细.包装数量",
PICK_TICKET_DETAIL.EXPECTED_QUANTITY_BU AS "明细.数量"
FROM WMS_PICK_TICKET PICK_TICKET
LEFT JOIN WMS_BILL_TYPE WMS_BILL_TYPE ON WMS_BILL_TYPE.ID = PICK_TICKET.BILL_TYPE_ID
LEFT JOIN WMS_ORGANIZATION COMPANY ON COMPANY.ID = PICK_TICKET.COMPANY_ID
LEFT JOIN WMS_ORGANIZATION CARRIER ON CARRIER.ID = PICK_TICKET.CARRIER_ID
LEFT JOIN WMS_DOCK DOCK ON DOCK.ID = PICK_TICKET.DOCK_ID
LEFT JOIN WMS_PICK_TICKET_DETAIL PICK_TICKET_DETAIL ON PICK_TICKET_DETAIL.PICK_TICKET_ID = PICK_TICKET.ID
LEFT JOIN WMS_PACKAGE_UNIT PACKAGE_UNIT ON PACKAGE_UNIT.ID = PICK_TICKET_DETAIL.PICK_TICKET_ID
LEFT JOIN WMS_ITEM ITEM ON ITEM.ID = PICK_TICKET_DETAIL.ITEM_ID
WHERE 1=1
/~发货单序号: AND PICK_TICKET.ID = {发货单序号}~/