SELECT 
 INV_EXT.LOCATION_ID AS "组号",
 INV_EXT.ITEM_ID AS "库存明细.货品序号"
 FROM WMS_INVENTORY_EXTEND INV_EXT
 WHERE 1=1
 /~托盘号: AND INV_EXT.PALLET = {托盘号}~/
 GROUP BY INV_EXT.LOCATION_ID, INV_EXT.ITEM_ID
