SELECT 
 INV.STATUS AS "组号",
 INV.ID AS "库存.库存序号", 
 COMPANY.NAME AS "库存.货主",
 ITEM_KEY.ID AS "库存.批次序号",
 ITEM.ID AS "库存.货品序号", 
 ITEM.CODE AS "库存.货品代码", 
 ITEM.PRECISION_BU AS "库存.货品基本单位精度", 
 UNIT.ID AS "库存.包装序号",
 UNIT.UNIT AS "库存.包装单位",
 UNIT.CONVERT_FIGURE AS "库存.包装件装量",
 INV.STATUS AS "库存.库存状态",
 (INV.QUANTITY_BU - INV.ALLOCATED_QUANTITY_BU) AS "库存.库存数量",
 LOC.ID AS "库存.库位序号",
 ITEM_KEY.STORAGE_DATE AS "库存.存货日期"
 FROM WMS_INVENTORY_EXTEND INV_EXT
 LEFT JOIN WMS_INVENTORY INV ON INV.ID = INV_EXT.INVENTORY_ID
 LEFT JOIN WMS_ITEM_KEY ITEM_KEY ON ITEM_KEY.ID = INV.ITEM_KEY_ID
 LEFT JOIN WMS_ITEM ITEM ON ITEM.ID = ITEM_KEY.ITEM_ID
 LEFT JOIN WMS_LOCATION LOC ON LOC.ID = INV_EXT.LOCATION_ID
 LEFT JOIN WMS_PACKAGE_UNIT UNIT ON UNIT.ID = INV.PACKAGE_UNIT_ID
 LEFT JOIN WMS_ORGANIZATION SUP ON SUP.ID = ITEM_KEY.SUPPLIER_ID
 LEFT JOIN WMS_ORGANIZATION COMPANY ON COMPANY.ID = ITEM.COMPANY_ID
WHERE 1=1
 AND LOC.STATUS = 'ENABLED'
 AND LOC.COUNT_LOCK = 'N'
 AND LOC.TYPE = 'STORAGE'
 AND LOC.ZONE_NO > 0
 AND INV.QUANTITY_BU - INV.ALLOCATED_QUANTITY_BU > 0
 AND (SELECT COUNT(*) FROM WMS_INVENTORY_EXTEND INV_EXT WHERE INV_EXT.INVENTORY_ID = INV.ID AND INV_EXT.PALLET <> '-') = 0
 /~仓库序号: AND LOC.WAREHOUSE_ID = {仓库序号}~/
 /~货品序号: AND ITEM.ID = {货品序号}~/
 AND (LOC.ID NOT IN (SELECT LOCATION.ID 
       FROM WMS_LOCATION LOCATION
 		LEFT JOIN WMS_ZONE AREA ON AREA.ID = LOCATION.ZONE_ID
       WHERE 1 <> 1
       /~出锁拼接条件: OR #{出锁拼接条件}~/
	)
 )
 AND (LOC.ID IN (SELECT LOCATION.ID 
       FROM WMS_LOCATION LOCATION
 		LEFT JOIN WMS_ZONE AREA ON AREA.ID = LOCATION.ZONE_ID
       WHERE 1 <> 1
       /~拣货区拼接条件: OR #{拣货区拼接条件}~/
	)
 )
 